server:
  port: 9000
  servlet:
    context-path: /redis

spring:
  redis:
    host: 192.168.83.100
    port: 6379
    password: redis@6379
    database: 0
    jedis:
      pool:
        max-idle: 100
        min-idle: 20
        max-active: 80
        max-wait: 5000
        time-between-eviction-runs: 3000

